авто:
  - авто
  - ароматизатор
  - смазка
  - воронка
  - '#2F3338'
алкоголь:
  - вино
  - водка
  - джин
  - пиво
  - '#764F37'
аптека:
  - глина
  - аскорбинка
  - ригевидон
  - глицин
  - миг
  - найз
  - таб
  - капс
  - '#4783B3'
бакалея:
  - щи
  - рожки
  - макаронные изделия
  - макароны
  - спагетти
  - вермишель
  - масло подсолнечное
  - масло раф дез
  - масло оливковое
  - '#F4D88E'
быт:
  - банка
  - стерилизатор
  - отбеливатель
  - ящик
  - булавки
  - корзина
  - с/порошок
  - сетка
  - ск-ть
  - солонка
  - массажер
  - средство дезинфицирующее
  - мешо*ки* д/мусора
  - перчатки
  - освежитель
  - мыло
  - прокладки
  - пакет
  - форма для пасхи
  - бульонница
  - термоэтикетка
  - з/паста
  - туалетная
  - ватные палочки
  - гель для унитаза
  - шамп
  - дез(-|одоран)т
  - антипер
  - заколка
  - клей
  - зажимы
  - штора
  - комарофф
  - крем
  - средство
  - салфетки
  - ополаскиватель
  - губки
  - ватные диски
  - '#DF0E25'
выпечка:
  - желатин
  - ванилин
  - разрыхлитель
  - бумага для выпечки
  - дрожжи
  - маргарин
  - сода
  - тесто
  - '#B8E427'
гигиена:
  - гель д/д
  - шампунь
  - зубная щетка
  - '#F9B082'
грибы:
  - гриб
  - шампиньоны
  - '#959286'
закуски:
  - чипсы
  - закуск[аи]
  - путассу нарезка
  - колбаски мини салями
  - снэки
  - '#D76F26'
зелень:
  - зелень
  - базилик
  - каркаде
  - кинза
  - лук зеленый
  - мята
  - петрушка
  - розмарин
  - тимьян
  - укроп
  - шпинат
  - щавель
  - '#C6DCA2'
зерновые:
  - геркулес
  - гречн*е*к*в*ая*
  - рис
  - пшено
  - пшеничная крупа
  - мука
  - крахмал
  - отруби
  - '#A8744F'
канцтовары:
  - карандаш.*
  - ручка гел
  - '#EBD028'
молоко:
  - морож(|еное)
  - молоко
  - ряженка
  - снежок
  - сыр
  - йогурт
  - кефир
  - масло (.*)слив(|оч)(|ное)
  - сметана
  - '#5CA2D0'
мясо:
  - курица
  - грудка
  - курин
  - печень
  - бройлер
  - свинина
  - свин
  - говядина
  - говяж
  - ветчина
  - колбаса
  - паштет
  - уголь
  - сосиски
  - пельмени
  - '#F77175'
напитки:
  - чай
  - кофе
  - какао
  - кола
  - цикорий
  - сок
  - морс
  - квас
  - вода
  - напиток
  - '#F5B985'
овощи:
  - томаты
  - картофель
  - морковь
  - свекла
  - редис
  - имбирь
  - лук
  - чеснок
  - перец болгарский
  - помидоры
  - баклажан
  - томатная паста
  - кабачки
  - огурцы
  - тыква
  - бобы
  - горох
  - зеленый горошек
  - фасоль
  - чечевица
  - соевый
  - брокколи
  - салат
  - капуста
  - кукуруза
  - сельдерей
  - спаржа
  - дайкон
  - '#D4FCCC'
одежда:
  - шляпа
  - '#EEC0A5'
орехи:
  - арахис
  - орех
  - кешью
  - миндаль
  - фисташк(и|а)
  - фундук
  - кокос
  - '#F1A46D'
приправы:
  - зира
  - кардамон
  - кунжут
  - анис
  - горчица
  - чиа
  - семена
  - семечки
  - семя
  - льняное
  - тмин
  - гвоздика
  - корица
  - куркума
  - лавровый лист
  - кориандр
  - мускатный орех
  - орегано
  - паприка
  - перец
  - соль
  - шафран
  - приправа
  - '#A6864E'
ремонт:
  - подводка д/воды
  - прокладка ред
  - '#C6B7A9'
рыба:
  - сельд(ь|и)
  - скумбрия
  - икра
  - '#FCECD4'
сладкое:
  - козинак
  - сгущенное молоко
  - молоко сгущенное
  - шоколад
  - конфет[ыа]
  - коржи
  - мармелад
  - мед
  - мёд
  - мороженое
  - мор плом
  - печенье
  - щербет
  - жев(|ательная) рез(|ин|инка)
  - зефир
  - ирис
  - карамель
  - кекс
  - сахар(|ный песок)
  - драже шок
  - халва
  - готовый завтрак
  - вафли
  - '#F5740A'
соусы:
  - майонез
  - горчица
  - кетчуп
  - хрен
  - '#FBF6D4'
фрукты:
  - абрикос
  - айва
  - ананас
  - апельсины*
  - арбуз
  - бананы*
  - гранат
  - грейпфрут
  - груша
  - дыня
  - инжир
  - киви
  - лайм
  - лимоны*
  - мандарин
  - маслины
  - нектарин
  - оливки
  - персик
  - слива
  - хурма
  - яблоки
  - '#DE374F'
хлеб:
  - хлеб
  - лаваш
  - пончики
  - батон(|чик)
  - буханка
  - сайка
  - булочка
  - '#C1A590'
цветы:
  - маргаритка
  - ромашка
  - '#6B273B'
электроника:
  - элем.(| )пит.
  - батарейка
  - лампа
  - розетка
  - '#C39C6E'
ягоды:
  - бузина
  - виноград
  - вишня
  - голубика
  - ежевика
  - клубника
  - клюква
  - крыжовник
  - малина
  - смородина
  - годжи
  - изюм
  - алыча
  - '#FCE4BA'
яйца:
  - яйца
  - яйцо
  - '#D68E5D'
