фрукты: 
  - абрикос
  - айва
  - ананас
  - апельсины*
  - арбуз
  - бананы*
  - гранат
  - грейпфрут
  - груша
  - дыня
  - инжир
  - киви
  - лайм
  - лимоны*
  - мандарин
  - маслины
  - нектарин
  - оливки
  - персик
  - слива
  - хурма
  - яблоки
аптека:
  - глина
  - аскорбинка
  - ригевидон
ягоды: 
  - бузина
  - виноград
  - вишня
  - голубика
  - ежевика
  - клубника
  - клюква
  - крыжовник
  - малина
  - смородина
  - годжи
  - изюм
закуски:
  - чипсы
  - закуск[аи]
  - путассу нарезка
  - колбаски мини салями
  - снэки
овощи:
  - томаты
  - картофель
  - морковь
  - свекла
  - редис
  - имбирь
  - лук
  - чеснок
  - перец болгарский
  - помидоры
  - баклажан
  - томатная паста
  - кабачки
  - огурцы
  - тыква
  - бобы
  - горох
  - зеленый горошек
  - фасоль
  - чечевица
  - соевый
  - брокколи
  - салат
  - капуста
  - кукуруза
  - сельдерей
  - спаржа
  - дайкон
зелень: 
  - базилик
  - каркаде
  - кинза
  - лук зеленый
  - мята
  - петрушка
  - розмарин
  - тимьян
  - укроп
  - шпинат
  - щавель
приправы: 
  - зира
  - кардамон
  - кунжут
  - анис
  - горчица
  - чиа
  - семена
  - семечки
  - семя
  - льняное
  - тмин
  - гвоздика
  - корица
  - куркума
  - лавровый лист
  - кориандр
  - мускатный орех
  - орегано
  - паприка
  - перец
  - соль
  - шафран
  - приправа
грибы:
  - гриб
  - шампиньоны
зерновые:
  - геркулес
  - гречн*е*к*в*ая*
  - рис
  - пшено
  - пшеничная крупа
  - мука
  - крахмал
  - отруби
сладкое:
  - козинак
  - сгущенное молоко
  - молоко сгущенное
  - шоколад
  - конфет[ыа]
  - коржи
  - мармелад
  - мед
  - мёд
  - мороженое
  - печенье
  - щербет
  - жев(|ательная) рез(|инка)
  - зефир
  - ирис
  - карамель
  - кекс
  - сахар(|ный песок)
  - драже шок
  - халва
  - готовый завтрак
  - вафли
орехи:
  - арахис
  - орех
  - кешью
  - миндаль
  - фисташки
  - фундук
  - кокос
хлеб:
  - хлеб
  - лаваш
  - пончики
  - батон(|чик)
  - буханка
  - сайка
  - булочка
яйца:
  - яйца
  - яйцо
молоко: 
  - молоко
  - ряженка
  - снежок
  - сыр
  - йогурт
  - кефир
  - масло (.*)слив(|оч)(|ное)
  - сметана
напитки:
  - чай
  - кофе
  - какао
  - кола
  - цикорий
  - сок
  - морс
  - квас
алкоголь:
  - вино
  - водка
  - джин
  - пиво
соусы:
  - майонез
  - горчица
  - кетчуп
  - хрен
рыба:
  - сельд(ь|и)
  - скумбрия
  - икра
бакалея:
  - рожки
  - макаронные изделия
  - макароны
  - спагетти
  - вермишель
  - масло подсолнечное
  - масло раф дез
  - масло оливковое
мясо:
  - курица
  - курин
  - печень
  - бройлер
  - свинина
  - свин
  - говядина
  - говяж
  - ветчина
  - колбаса
  - паштет
  - сосиски
  - пельмени
электроника:
  - элем. пит.
  - батарейка
  - лампа
  - розетка
быт:
  - с/порошок
  - сетка
  - ск-ть
  - солонка
  - массажер
  - средство дезинфицирующее
  - мешо*ки* д/мусора
  - перчатки
  - освежитель
  - мыло
  - прокладки
  - пакет
  - форма для пасхи
  - бульонница
  - термоэтикетка
  - з/паста
  - туалетная бумага
  - ватные палочки
  - гель для унитаза
  - клей
  - зажимы
  - штора
гигиена:
  - гель д/д
  - шампунь
  - зубная щетка
выпечка:
  - желатин
  - ванилин
  - разрыхлитель
  - бумага для выпечки
  - дрожжи
  - маргарин
  - тесто
ремонт:
  - подводка д/воды
  - прокладка ред
цветы:
  - маргаритка
  - ромашка
авто:
  - авто
  - ароматизатор
канцтовары:
  - карандаш.*
